# Generated by Django 5.0.6 on 2024-06-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massages', '0006_alter_messages_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/files'),
        ),
        migrations.AddField(
            model_name='messages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
