# Generated by Django 5.0.6 on 2024-06-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/videos/'),
        ),
    ]
